package com.miaoshaproject.dao;

import com.miaoshaproject.dataobjects.ItemStockDO;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Jul 18 22:30:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Jul 18 22:30:05 CST 2020
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Jul 18 22:30:05 CST 2020
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Jul 18 22:30:05 CST 2020
     */
    ItemStockDO selectByPrimaryKey(Integer id);


    /**
     * 用过itemId获取到库存的信息
     *
     * @author 多宝
     * @since 2020/7/26 14:21
     * @param  itemId     商品ID
     * @return com.miaoshaproject.dataobjects.ItemStockDO
     */
    ItemStockDO selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Jul 18 22:30:05 CST 2020
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Jul 18 22:30:05 CST 2020
     */
    int updateByPrimaryKey(ItemStockDO record);
}