server:
  port: 8080
mybatis:
  mapper-locations: classpath:/mapping/*.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.5.1:3306/miaosha?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  devtools:
    restart:
      enabled: true